import { ClerkProvider } from "@clerk/nextjs";
import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import Header from "./_components/Header";

const inter = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'File Share App',
  description: 'Generated by create next app',
}

/**
 * Renders the root layout of the application.
 *
 * @param {object} children - The children elements to be rendered.
 * @return {JSX.Element} The root layout component.
 */
export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
