import { ClerkProvider } from "@clerk/nextjs/app-beta";
import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import Header from './_components/Header'

const inter = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'File Share App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
