import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { AuthContextProvider } from "../contexts/AuthContext";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "File Share App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
